# Site settings
title: "VMware Cloud: A Hands-On Guide"
description: > # this means to ignore newlines until "baseurl:"
  A hands-on guide for VMware Cloud.
baseurl: "/vmcbook" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown


exclude:
  - .gitignore
  - .jekyll-cache
  - readme.md
